/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerId = IDL.Nat;
export const CoconutType = IDL.Variant({
  'tallu' : IDL.Null,
  'rasi' : IDL.Null,
  'others' : IDL.Null,
});
export const CoconutItem = IDL.Record({
  'specifyType' : IDL.Text,
  'coconutType' : CoconutType,
  'quantity' : IDL.Nat,
});
export const CoconutBatchEntryInput = IDL.Record({
  'customerName' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'createdByName' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : CustomerId,
  'items' : IDL.Vec(CoconutItem),
});
export const EntryId = IDL.Nat;
export const CoconutEntryInput = IDL.Record({
  'customerName' : IDL.Text,
  'specifyType' : IDL.Text,
  'coconutType' : CoconutType,
  'vehicleNumber' : IDL.Text,
  'createdByName' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'customerId' : CustomerId,
});
export const CustomerInput = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const ItemType = IDL.Variant({
  'dry' : IDL.Null,
  'wet' : IDL.Null,
  'motta' : IDL.Null,
  'both' : IDL.Null,
  'husk' : IDL.Null,
  'others' : IDL.Null,
});
export const HuskEntryInput = IDL.Record({
  'customerName' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'createdByName' : IDL.Text,
  'notes' : IDL.Text,
  'itemType' : ItemType,
  'quantity' : IDL.Nat,
  'customerId' : CustomerId,
});
export const HuskItem = IDL.Record({
  'itemType' : ItemType,
  'quantity' : IDL.Nat,
});
export const HuskBatchEntryInput = IDL.Record({
  'customerName' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'createdByName' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : CustomerId,
  'items' : IDL.Vec(HuskItem),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VehicleId = IDL.Nat;
export const Time = IDL.Int;
export const CoconutBatchEntry = IDL.Record({
  'id' : EntryId,
  'customerName' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'createdByName' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : CustomerId,
  'items' : IDL.Vec(CoconutItem),
});
export const CoconutEntry = IDL.Record({
  'id' : EntryId,
  'customerName' : IDL.Text,
  'specifyType' : IDL.Text,
  'coconutType' : CoconutType,
  'vehicleNumber' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'createdByName' : IDL.Text,
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'customerId' : CustomerId,
});
export const Customer = IDL.Record({
  'id' : CustomerId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const HuskEntry = IDL.Record({
  'id' : EntryId,
  'customerName' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'createdByName' : IDL.Text,
  'notes' : IDL.Text,
  'itemType' : ItemType,
  'quantity' : IDL.Nat,
  'customerId' : CustomerId,
});
export const HuskBatchEntry = IDL.Record({
  'id' : EntryId,
  'customerName' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'createdByName' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : CustomerId,
  'items' : IDL.Vec(HuskItem),
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
});
export const Vehicle = IDL.Record({
  'id' : VehicleId,
  'vehicleNumber' : IDL.Text,
  'usageCount' : IDL.Nat,
  'lastUsed' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CoconutBatchReportFilter = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'coconutType' : IDL.Opt(CoconutType),
  'vehicleNumber' : IDL.Opt(IDL.Text),
  'customerId' : IDL.Opt(CustomerId),
  'startDate' : IDL.Opt(Time),
});
export const CoconutBatchReport = IDL.Record({
  'entries' : IDL.Vec(CoconutBatchEntry),
  'totalQuantity' : IDL.Nat,
});
export const CoconutReport = IDL.Record({
  'entries' : IDL.Vec(CoconutEntry),
  'totalQuantity' : IDL.Nat,
});
export const ReportFilter = IDL.Record({
  'endDate' : IDL.Opt(Time),
  'userId' : IDL.Opt(IDL.Principal),
  'vehicleNumber' : IDL.Opt(IDL.Text),
  'itemType' : IDL.Opt(ItemType),
  'customerId' : IDL.Opt(CustomerId),
  'startDate' : IDL.Opt(Time),
});
export const HuskBatchReport = IDL.Record({
  'entries' : IDL.Vec(HuskBatchEntry),
  'totalQuantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCoconutBatchEntry' : IDL.Func([CoconutBatchEntryInput], [EntryId], []),
  'addCoconutEntry' : IDL.Func([CoconutEntryInput], [EntryId], []),
  'addCustomer' : IDL.Func([CustomerInput], [CustomerId], []),
  'addEntry' : IDL.Func([HuskEntryInput], [EntryId], []),
  'addHuskBatchEntry' : IDL.Func([HuskBatchEntryInput], [EntryId], []),
  'addNote' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCoconutBatchEntry' : IDL.Func([EntryId], [], []),
  'deleteCoconutEntry' : IDL.Func([EntryId], [], []),
  'deleteCustomer' : IDL.Func([CustomerId], [], []),
  'deleteEntry' : IDL.Func([EntryId], [], []),
  'deleteHuskBatchEntry' : IDL.Func([EntryId], [], []),
  'deleteVehicle' : IDL.Func([VehicleId], [], []),
  'getAllCoconutBatchEntries' : IDL.Func(
      [],
      [IDL.Vec(CoconutBatchEntry)],
      ['query'],
    ),
  'getAllCoconutEntries' : IDL.Func([], [IDL.Vec(CoconutEntry)], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllEntries' : IDL.Func([], [IDL.Vec(HuskEntry)], ['query']),
  'getAllHuskBatchEntries' : IDL.Func([], [IDL.Vec(HuskBatchEntry)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCoconutBatchEntry' : IDL.Func([EntryId], [CoconutBatchEntry], ['query']),
  'getCoconutBatchReport' : IDL.Func(
      [CoconutBatchReportFilter],
      [CoconutBatchReport],
      ['query'],
    ),
  'getCoconutEntry' : IDL.Func([EntryId], [CoconutEntry], ['query']),
  'getCoconutReport' : IDL.Func(
      [
        IDL.Record({
          'endDate' : IDL.Opt(Time),
          'coconutType' : IDL.Opt(CoconutType),
          'vehicleNumber' : IDL.Opt(IDL.Text),
          'customerId' : IDL.Opt(CustomerId),
          'startDate' : IDL.Opt(Time),
        }),
      ],
      [CoconutReport],
      ['query'],
    ),
  'getCustomer' : IDL.Func([CustomerId], [Customer], ['query']),
  'getEntry' : IDL.Func([EntryId], [HuskEntry], ['query']),
  'getHuskBatchEntry' : IDL.Func([EntryId], [HuskBatchEntry], ['query']),
  'getHuskBatchReport' : IDL.Func([ReportFilter], [HuskBatchReport], ['query']),
  'getReport' : IDL.Func(
      [ReportFilter],
      [
        IDL.Record({
          'entries' : IDL.Vec(HuskEntry),
          'totalQuantity' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCoconutBatchEntry' : IDL.Func(
      [EntryId, CoconutBatchEntryInput],
      [],
      [],
    ),
  'updateCoconutEntry' : IDL.Func([EntryId, CoconutEntryInput], [], []),
  'updateCustomer' : IDL.Func([CustomerId, CustomerInput], [], []),
  'updateEntry' : IDL.Func([EntryId, HuskEntryInput], [], []),
  'updateHuskBatchEntry' : IDL.Func([EntryId, HuskBatchEntryInput], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerId = IDL.Nat;
  const CoconutType = IDL.Variant({
    'tallu' : IDL.Null,
    'rasi' : IDL.Null,
    'others' : IDL.Null,
  });
  const CoconutItem = IDL.Record({
    'specifyType' : IDL.Text,
    'coconutType' : CoconutType,
    'quantity' : IDL.Nat,
  });
  const CoconutBatchEntryInput = IDL.Record({
    'customerName' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'createdByName' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : CustomerId,
    'items' : IDL.Vec(CoconutItem),
  });
  const EntryId = IDL.Nat;
  const CoconutEntryInput = IDL.Record({
    'customerName' : IDL.Text,
    'specifyType' : IDL.Text,
    'coconutType' : CoconutType,
    'vehicleNumber' : IDL.Text,
    'createdByName' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'customerId' : CustomerId,
  });
  const CustomerInput = IDL.Record({
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const ItemType = IDL.Variant({
    'dry' : IDL.Null,
    'wet' : IDL.Null,
    'motta' : IDL.Null,
    'both' : IDL.Null,
    'husk' : IDL.Null,
    'others' : IDL.Null,
  });
  const HuskEntryInput = IDL.Record({
    'customerName' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'createdByName' : IDL.Text,
    'notes' : IDL.Text,
    'itemType' : ItemType,
    'quantity' : IDL.Nat,
    'customerId' : CustomerId,
  });
  const HuskItem = IDL.Record({ 'itemType' : ItemType, 'quantity' : IDL.Nat });
  const HuskBatchEntryInput = IDL.Record({
    'customerName' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'createdByName' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : CustomerId,
    'items' : IDL.Vec(HuskItem),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VehicleId = IDL.Nat;
  const Time = IDL.Int;
  const CoconutBatchEntry = IDL.Record({
    'id' : EntryId,
    'customerName' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'createdByName' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : CustomerId,
    'items' : IDL.Vec(CoconutItem),
  });
  const CoconutEntry = IDL.Record({
    'id' : EntryId,
    'customerName' : IDL.Text,
    'specifyType' : IDL.Text,
    'coconutType' : CoconutType,
    'vehicleNumber' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'createdByName' : IDL.Text,
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'customerId' : CustomerId,
  });
  const Customer = IDL.Record({
    'id' : CustomerId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const HuskEntry = IDL.Record({
    'id' : EntryId,
    'customerName' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'createdByName' : IDL.Text,
    'notes' : IDL.Text,
    'itemType' : ItemType,
    'quantity' : IDL.Nat,
    'customerId' : CustomerId,
  });
  const HuskBatchEntry = IDL.Record({
    'id' : EntryId,
    'customerName' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'createdByName' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : CustomerId,
    'items' : IDL.Vec(HuskItem),
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
  });
  const Vehicle = IDL.Record({
    'id' : VehicleId,
    'vehicleNumber' : IDL.Text,
    'usageCount' : IDL.Nat,
    'lastUsed' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CoconutBatchReportFilter = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'coconutType' : IDL.Opt(CoconutType),
    'vehicleNumber' : IDL.Opt(IDL.Text),
    'customerId' : IDL.Opt(CustomerId),
    'startDate' : IDL.Opt(Time),
  });
  const CoconutBatchReport = IDL.Record({
    'entries' : IDL.Vec(CoconutBatchEntry),
    'totalQuantity' : IDL.Nat,
  });
  const CoconutReport = IDL.Record({
    'entries' : IDL.Vec(CoconutEntry),
    'totalQuantity' : IDL.Nat,
  });
  const ReportFilter = IDL.Record({
    'endDate' : IDL.Opt(Time),
    'userId' : IDL.Opt(IDL.Principal),
    'vehicleNumber' : IDL.Opt(IDL.Text),
    'itemType' : IDL.Opt(ItemType),
    'customerId' : IDL.Opt(CustomerId),
    'startDate' : IDL.Opt(Time),
  });
  const HuskBatchReport = IDL.Record({
    'entries' : IDL.Vec(HuskBatchEntry),
    'totalQuantity' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCoconutBatchEntry' : IDL.Func([CoconutBatchEntryInput], [EntryId], []),
    'addCoconutEntry' : IDL.Func([CoconutEntryInput], [EntryId], []),
    'addCustomer' : IDL.Func([CustomerInput], [CustomerId], []),
    'addEntry' : IDL.Func([HuskEntryInput], [EntryId], []),
    'addHuskBatchEntry' : IDL.Func([HuskBatchEntryInput], [EntryId], []),
    'addNote' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCoconutBatchEntry' : IDL.Func([EntryId], [], []),
    'deleteCoconutEntry' : IDL.Func([EntryId], [], []),
    'deleteCustomer' : IDL.Func([CustomerId], [], []),
    'deleteEntry' : IDL.Func([EntryId], [], []),
    'deleteHuskBatchEntry' : IDL.Func([EntryId], [], []),
    'deleteVehicle' : IDL.Func([VehicleId], [], []),
    'getAllCoconutBatchEntries' : IDL.Func(
        [],
        [IDL.Vec(CoconutBatchEntry)],
        ['query'],
      ),
    'getAllCoconutEntries' : IDL.Func([], [IDL.Vec(CoconutEntry)], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllEntries' : IDL.Func([], [IDL.Vec(HuskEntry)], ['query']),
    'getAllHuskBatchEntries' : IDL.Func(
        [],
        [IDL.Vec(HuskBatchEntry)],
        ['query'],
      ),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCoconutBatchEntry' : IDL.Func(
        [EntryId],
        [CoconutBatchEntry],
        ['query'],
      ),
    'getCoconutBatchReport' : IDL.Func(
        [CoconutBatchReportFilter],
        [CoconutBatchReport],
        ['query'],
      ),
    'getCoconutEntry' : IDL.Func([EntryId], [CoconutEntry], ['query']),
    'getCoconutReport' : IDL.Func(
        [
          IDL.Record({
            'endDate' : IDL.Opt(Time),
            'coconutType' : IDL.Opt(CoconutType),
            'vehicleNumber' : IDL.Opt(IDL.Text),
            'customerId' : IDL.Opt(CustomerId),
            'startDate' : IDL.Opt(Time),
          }),
        ],
        [CoconutReport],
        ['query'],
      ),
    'getCustomer' : IDL.Func([CustomerId], [Customer], ['query']),
    'getEntry' : IDL.Func([EntryId], [HuskEntry], ['query']),
    'getHuskBatchEntry' : IDL.Func([EntryId], [HuskBatchEntry], ['query']),
    'getHuskBatchReport' : IDL.Func(
        [ReportFilter],
        [HuskBatchReport],
        ['query'],
      ),
    'getReport' : IDL.Func(
        [ReportFilter],
        [
          IDL.Record({
            'entries' : IDL.Vec(HuskEntry),
            'totalQuantity' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCoconutBatchEntry' : IDL.Func(
        [EntryId, CoconutBatchEntryInput],
        [],
        [],
      ),
    'updateCoconutEntry' : IDL.Func([EntryId, CoconutEntryInput], [], []),
    'updateCustomer' : IDL.Func([CustomerId, CustomerInput], [], []),
    'updateEntry' : IDL.Func([EntryId, HuskEntryInput], [], []),
    'updateHuskBatchEntry' : IDL.Func([EntryId, HuskBatchEntryInput], [], []),
  });
};

export const init = ({ IDL }) => { return []; };