/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CoconutBatchEntry {
  'id' : EntryId,
  'customerName' : string,
  'paymentStatus' : PaymentStatus,
  'vehicleNumber' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'createdByName' : string,
  'notes' : string,
  'lastModifiedAt' : [] | [Time],
  'customerId' : CustomerId,
  'items' : Array<CoconutItem>,
  'paymentAmount' : [] | [bigint],
  'lastModifiedByName' : [] | [string],
}
export interface CoconutBatchEntryInput {
  'customerName' : string,
  'vehicleNumber' : string,
  'createdByName' : string,
  'notes' : string,
  'customerId' : CustomerId,
  'items' : Array<CoconutItem>,
}
export interface CoconutBatchReport {
  'pendingCount' : bigint,
  'totalPaymentAmount' : bigint,
  'entries' : Array<CoconutBatchEntry>,
  'paidCount' : bigint,
  'totalQuantity' : bigint,
}
export interface CoconutBatchReportFilter {
  'paymentStatus' : [] | [PaymentStatus],
  'endDate' : [] | [Time],
  'coconutType' : [] | [CoconutType],
  'vehicleNumber' : [] | [string],
  'customerId' : [] | [CustomerId],
  'startDate' : [] | [Time],
}
export interface CoconutItem {
  'specifyType' : string,
  'coconutType' : CoconutType,
  'quantity' : bigint,
}
export type CoconutType = { 'tallu' : null } |
  { 'rasi' : null } |
  { 'others' : null };
export type CustomerId = bigint;
export interface CustomerInputV2 {
  'customerType' : string,
  'name' : string,
  'phone' : string,
  'location' : string,
}
export interface CustomerV2 {
  'id' : CustomerId,
  'customerType' : string,
  'name' : string,
  'createdAt' : Time,
  'phone' : string,
  'location' : string,
}
export type EntryId = bigint;
export interface HuskBatchEntry {
  'id' : EntryId,
  'customerName' : string,
  'paymentStatus' : PaymentStatus,
  'vehicleNumber' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'createdByName' : string,
  'notes' : string,
  'lastModifiedAt' : [] | [Time],
  'customerId' : CustomerId,
  'items' : Array<HuskItem>,
  'paymentAmount' : [] | [bigint],
  'lastModifiedByName' : [] | [string],
}
export interface HuskBatchEntryInput {
  'customerName' : string,
  'vehicleNumber' : string,
  'createdByName' : string,
  'notes' : string,
  'customerId' : CustomerId,
  'items' : Array<HuskItem>,
}
export interface HuskBatchReport {
  'pendingCount' : bigint,
  'totalPaymentAmount' : bigint,
  'entries' : Array<HuskBatchEntry>,
  'paidCount' : bigint,
  'totalQuantity' : bigint,
}
export interface HuskItem { 'itemType' : ItemType, 'quantity' : bigint }
export type ItemType = { 'dry' : null } |
  { 'wet' : null } |
  { 'motta' : null } |
  { 'both' : null } |
  { 'husk' : null } |
  { 'others' : null };
export interface Note {
  'id' : bigint,
  'content' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
}
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null };
export interface ReportFilter {
  'paymentStatus' : [] | [PaymentStatus],
  'endDate' : [] | [Time],
  'userId' : [] | [string],
  'vehicleNumber' : [] | [string],
  'itemType' : [] | [ItemType],
  'customerId' : [] | [CustomerId],
  'startDate' : [] | [Time],
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'staff' : null } |
  { 'driver' : null };
export interface Vehicle {
  'id' : VehicleId,
  'vehicleNumber' : string,
  'usageCount' : bigint,
  'lastUsed' : Time,
}
export type VehicleId = bigint;
export interface _SERVICE {
  'addCoconutBatchEntry' : ActorMethod<
    [string, string, CoconutBatchEntryInput],
    EntryId
  >,
  'addCoconutBatchEntryWithDate' : ActorMethod<
    [string, string, CoconutBatchEntryInput, bigint],
    EntryId
  >,
  'addCustomer' : ActorMethod<[string, string, CustomerInputV2], CustomerId>,
  'addHuskBatchEntry' : ActorMethod<
    [string, string, HuskBatchEntryInput],
    EntryId
  >,
  'addHuskBatchEntryWithDate' : ActorMethod<
    [string, string, HuskBatchEntryInput, bigint],
    EntryId
  >,
  'addNote' : ActorMethod<[string, string, string], bigint>,
  'adminChangeUserPin' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminChangeUserRole' : ActorMethod<
    [string, string, string, UserRole],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminCreateUser' : ActorMethod<
    [string, string, string, string, string, UserRole],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteUser' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminListUsers' : ActorMethod<
    [string, string],
    [] | [Array<{ 'username' : string, 'name' : string, 'role' : UserRole }>]
  >,
  'changeOwnPin' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteCoconutBatchEntry' : ActorMethod<[string, string, EntryId], undefined>,
  'deleteCustomer' : ActorMethod<[string, string, CustomerId], undefined>,
  'deleteHuskBatchEntry' : ActorMethod<[string, string, EntryId], undefined>,
  'deleteVehicle' : ActorMethod<[string, string, VehicleId], undefined>,
  'getAllCoconutBatchEntries' : ActorMethod<
    [string, string],
    Array<CoconutBatchEntry>
  >,
  'getAllCoconutCustomers' : ActorMethod<[string, string], Array<CustomerV2>>,
  'getAllCustomers' : ActorMethod<[string, string], Array<CustomerV2>>,
  'getAllHuskBatchEntries' : ActorMethod<
    [string, string],
    Array<HuskBatchEntry>
  >,
  'getAllHuskCustomers' : ActorMethod<[string, string], Array<CustomerV2>>,
  'getAllNotes' : ActorMethod<[string, string], Array<Note>>,
  'getAllVehicles' : ActorMethod<[string, string], Array<Vehicle>>,
  'getCoconutBatchReport' : ActorMethod<
    [string, string, CoconutBatchReportFilter],
    CoconutBatchReport
  >,
  'getHuskBatchReport' : ActorMethod<
    [string, string, ReportFilter],
    HuskBatchReport
  >,
  'loginUser' : ActorMethod<
    [string, string],
    [] | [{ 'username' : string, 'name' : string, 'role' : UserRole }]
  >,
  'updateCoconutBatchEntry' : ActorMethod<
    [string, string, EntryId, CoconutBatchEntryInput],
    undefined
  >,
  'updateCoconutBatchPayment' : ActorMethod<
    [string, string, EntryId, PaymentStatus, [] | [bigint]],
    undefined
  >,
  'updateCustomer' : ActorMethod<
    [string, string, CustomerId, CustomerInputV2],
    undefined
  >,
  'updateHuskBatchEntry' : ActorMethod<
    [string, string, EntryId, HuskBatchEntryInput],
    undefined
  >,
  'updateHuskBatchPayment' : ActorMethod<
    [string, string, EntryId, PaymentStatus, [] | [bigint]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];