/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CoconutBatchEntry {
  'id' : EntryId,
  'customerName' : string,
  'vehicleNumber' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'createdByName' : string,
  'notes' : string,
  'customerId' : CustomerId,
  'items' : Array<CoconutItem>,
}
export interface CoconutBatchEntryInput {
  'customerName' : string,
  'vehicleNumber' : string,
  'createdByName' : string,
  'notes' : string,
  'customerId' : CustomerId,
  'items' : Array<CoconutItem>,
}
export interface CoconutBatchReport {
  'entries' : Array<CoconutBatchEntry>,
  'totalQuantity' : bigint,
}
export interface CoconutBatchReportFilter {
  'endDate' : [] | [Time],
  'coconutType' : [] | [CoconutType],
  'vehicleNumber' : [] | [string],
  'customerId' : [] | [CustomerId],
  'startDate' : [] | [Time],
}
export interface CoconutEntry {
  'id' : EntryId,
  'customerName' : string,
  'specifyType' : string,
  'coconutType' : CoconutType,
  'vehicleNumber' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'createdByName' : string,
  'notes' : string,
  'quantity' : bigint,
  'customerId' : CustomerId,
}
export interface CoconutEntryInput {
  'customerName' : string,
  'specifyType' : string,
  'coconutType' : CoconutType,
  'vehicleNumber' : string,
  'createdByName' : string,
  'notes' : string,
  'quantity' : bigint,
  'customerId' : CustomerId,
}
export interface CoconutItem {
  'specifyType' : string,
  'coconutType' : CoconutType,
  'quantity' : bigint,
}
export interface CoconutReport {
  'entries' : Array<CoconutEntry>,
  'totalQuantity' : bigint,
}
export type CoconutType = { 'tallu' : null } |
  { 'rasi' : null } |
  { 'others' : null };
export interface Customer {
  'id' : CustomerId,
  'name' : string,
  'createdAt' : Time,
  'phone' : string,
  'location' : string,
}
export type CustomerId = bigint;
export interface CustomerInput {
  'name' : string,
  'phone' : string,
  'location' : string,
}
export type EntryId = bigint;
export interface HuskBatchEntry {
  'id' : EntryId,
  'customerName' : string,
  'vehicleNumber' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'createdByName' : string,
  'notes' : string,
  'customerId' : CustomerId,
  'items' : Array<HuskItem>,
}
export interface HuskBatchEntryInput {
  'customerName' : string,
  'vehicleNumber' : string,
  'createdByName' : string,
  'notes' : string,
  'customerId' : CustomerId,
  'items' : Array<HuskItem>,
}
export interface HuskBatchReport {
  'entries' : Array<HuskBatchEntry>,
  'totalQuantity' : bigint,
}
export interface HuskEntry {
  'id' : EntryId,
  'customerName' : string,
  'vehicleNumber' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'createdByName' : string,
  'notes' : string,
  'itemType' : ItemType,
  'quantity' : bigint,
  'customerId' : CustomerId,
}
export interface HuskEntryInput {
  'customerName' : string,
  'vehicleNumber' : string,
  'createdByName' : string,
  'notes' : string,
  'itemType' : ItemType,
  'quantity' : bigint,
  'customerId' : CustomerId,
}
export interface HuskItem { 'itemType' : ItemType, 'quantity' : bigint }
export type ItemType = { 'dry' : null } |
  { 'wet' : null } |
  { 'motta' : null } |
  { 'both' : null } |
  { 'husk' : null } |
  { 'others' : null };
export interface Note {
  'id' : bigint,
  'content' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
}
export interface ReportFilter {
  'endDate' : [] | [Time],
  'userId' : [] | [Principal],
  'vehicleNumber' : [] | [string],
  'itemType' : [] | [ItemType],
  'customerId' : [] | [CustomerId],
  'startDate' : [] | [Time],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vehicle {
  'id' : VehicleId,
  'vehicleNumber' : string,
  'usageCount' : bigint,
  'lastUsed' : Time,
}
export type VehicleId = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCoconutBatchEntry' : ActorMethod<[CoconutBatchEntryInput], EntryId>,
  'addCoconutEntry' : ActorMethod<[CoconutEntryInput], EntryId>,
  'addCustomer' : ActorMethod<[CustomerInput], CustomerId>,
  'addEntry' : ActorMethod<[HuskEntryInput], EntryId>,
  'addHuskBatchEntry' : ActorMethod<[HuskBatchEntryInput], EntryId>,
  'addNote' : ActorMethod<[string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCoconutBatchEntry' : ActorMethod<[EntryId], undefined>,
  'deleteCoconutEntry' : ActorMethod<[EntryId], undefined>,
  'deleteCustomer' : ActorMethod<[CustomerId], undefined>,
  'deleteEntry' : ActorMethod<[EntryId], undefined>,
  'deleteHuskBatchEntry' : ActorMethod<[EntryId], undefined>,
  'deleteVehicle' : ActorMethod<[VehicleId], undefined>,
  'getAllCoconutBatchEntries' : ActorMethod<[], Array<CoconutBatchEntry>>,
  'getAllCoconutEntries' : ActorMethod<[], Array<CoconutEntry>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllEntries' : ActorMethod<[], Array<HuskEntry>>,
  'getAllHuskBatchEntries' : ActorMethod<[], Array<HuskBatchEntry>>,
  'getAllNotes' : ActorMethod<[], Array<Note>>,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCoconutBatchEntry' : ActorMethod<[EntryId], CoconutBatchEntry>,
  'getCoconutBatchReport' : ActorMethod<
    [CoconutBatchReportFilter],
    CoconutBatchReport
  >,
  'getCoconutEntry' : ActorMethod<[EntryId], CoconutEntry>,
  'getCoconutReport' : ActorMethod<
    [
      {
        'endDate' : [] | [Time],
        'coconutType' : [] | [CoconutType],
        'vehicleNumber' : [] | [string],
        'customerId' : [] | [CustomerId],
        'startDate' : [] | [Time],
      },
    ],
    CoconutReport
  >,
  'getCustomer' : ActorMethod<[CustomerId], Customer>,
  'getEntry' : ActorMethod<[EntryId], HuskEntry>,
  'getHuskBatchEntry' : ActorMethod<[EntryId], HuskBatchEntry>,
  'getHuskBatchReport' : ActorMethod<[ReportFilter], HuskBatchReport>,
  'getReport' : ActorMethod<
    [ReportFilter],
    { 'entries' : Array<HuskEntry>, 'totalQuantity' : bigint }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCoconutBatchEntry' : ActorMethod<
    [EntryId, CoconutBatchEntryInput],
    undefined
  >,
  'updateCoconutEntry' : ActorMethod<[EntryId, CoconutEntryInput], undefined>,
  'updateCustomer' : ActorMethod<[CustomerId, CustomerInput], undefined>,
  'updateEntry' : ActorMethod<[EntryId, HuskEntryInput], undefined>,
  'updateHuskBatchEntry' : ActorMethod<
    [EntryId, HuskBatchEntryInput],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];