/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CustomerId = IDL.Nat;
export const CoconutType = IDL.Variant({
  'tallu' : IDL.Null,
  'rasi' : IDL.Null,
  'others' : IDL.Null,
});
export const CoconutItem = IDL.Record({
  'specifyType' : IDL.Text,
  'coconutType' : CoconutType,
  'quantity' : IDL.Nat,
});
export const CoconutBatchEntryInput = IDL.Record({
  'customerName' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'createdByName' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : CustomerId,
  'items' : IDL.Vec(CoconutItem),
});
export const EntryId = IDL.Nat;
export const CustomerInputV2 = IDL.Record({
  'customerType' : IDL.Text,
  'name' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const ItemType = IDL.Variant({
  'dry' : IDL.Null,
  'wet' : IDL.Null,
  'motta' : IDL.Null,
  'both' : IDL.Null,
  'husk' : IDL.Null,
  'others' : IDL.Null,
});
export const HuskItem = IDL.Record({
  'itemType' : ItemType,
  'quantity' : IDL.Nat,
});
export const HuskBatchEntryInput = IDL.Record({
  'customerName' : IDL.Text,
  'vehicleNumber' : IDL.Text,
  'createdByName' : IDL.Text,
  'notes' : IDL.Text,
  'customerId' : CustomerId,
  'items' : IDL.Vec(HuskItem),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'staff' : IDL.Null,
  'driver' : IDL.Null,
});
export const VehicleId = IDL.Nat;
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
});
export const Time = IDL.Int;
export const CoconutBatchEntry = IDL.Record({
  'id' : EntryId,
  'customerName' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'vehicleNumber' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'createdByName' : IDL.Text,
  'notes' : IDL.Text,
  'lastModifiedAt' : IDL.Opt(Time),
  'customerId' : CustomerId,
  'items' : IDL.Vec(CoconutItem),
  'paymentAmount' : IDL.Opt(IDL.Nat),
  'lastModifiedByName' : IDL.Opt(IDL.Text),
});
export const CustomerV2 = IDL.Record({
  'id' : CustomerId,
  'customerType' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const HuskBatchEntry = IDL.Record({
  'id' : EntryId,
  'customerName' : IDL.Text,
  'paymentStatus' : PaymentStatus,
  'vehicleNumber' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'createdByName' : IDL.Text,
  'notes' : IDL.Text,
  'lastModifiedAt' : IDL.Opt(Time),
  'customerId' : CustomerId,
  'items' : IDL.Vec(HuskItem),
  'paymentAmount' : IDL.Opt(IDL.Nat),
  'lastModifiedByName' : IDL.Opt(IDL.Text),
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
});
export const Vehicle = IDL.Record({
  'id' : VehicleId,
  'vehicleNumber' : IDL.Text,
  'usageCount' : IDL.Nat,
  'lastUsed' : Time,
});
export const CoconutBatchReportFilter = IDL.Record({
  'paymentStatus' : IDL.Opt(PaymentStatus),
  'endDate' : IDL.Opt(Time),
  'coconutType' : IDL.Opt(CoconutType),
  'vehicleNumber' : IDL.Opt(IDL.Text),
  'customerId' : IDL.Opt(CustomerId),
  'startDate' : IDL.Opt(Time),
});
export const CoconutBatchReport = IDL.Record({
  'pendingCount' : IDL.Nat,
  'totalPaymentAmount' : IDL.Nat,
  'entries' : IDL.Vec(CoconutBatchEntry),
  'paidCount' : IDL.Nat,
  'totalQuantity' : IDL.Nat,
});
export const ReportFilter = IDL.Record({
  'paymentStatus' : IDL.Opt(PaymentStatus),
  'endDate' : IDL.Opt(Time),
  'userId' : IDL.Opt(IDL.Text),
  'vehicleNumber' : IDL.Opt(IDL.Text),
  'itemType' : IDL.Opt(ItemType),
  'customerId' : IDL.Opt(CustomerId),
  'startDate' : IDL.Opt(Time),
});
export const HuskBatchReport = IDL.Record({
  'pendingCount' : IDL.Nat,
  'totalPaymentAmount' : IDL.Nat,
  'entries' : IDL.Vec(HuskBatchEntry),
  'paidCount' : IDL.Nat,
  'totalQuantity' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addCoconutBatchEntry' : IDL.Func(
      [IDL.Text, IDL.Text, CoconutBatchEntryInput],
      [EntryId],
      [],
    ),
  'addCoconutBatchEntryWithDate' : IDL.Func(
      [IDL.Text, IDL.Text, CoconutBatchEntryInput, IDL.Int],
      [EntryId],
      [],
    ),
  'addCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, CustomerInputV2],
      [CustomerId],
      [],
    ),
  'addHuskBatchEntry' : IDL.Func(
      [IDL.Text, IDL.Text, HuskBatchEntryInput],
      [EntryId],
      [],
    ),
  'addHuskBatchEntryWithDate' : IDL.Func(
      [IDL.Text, IDL.Text, HuskBatchEntryInput, IDL.Int],
      [EntryId],
      [],
    ),
  'addNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'adminChangeUserPin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminChangeUserRole' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, UserRole],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminCreateUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, UserRole],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminListUsers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Opt(
          IDL.Vec(
            IDL.Record({
              'username' : IDL.Text,
              'name' : IDL.Text,
              'role' : UserRole,
            })
          )
        ),
      ],
      ['query'],
    ),
  'changeOwnPin' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteCoconutBatchEntry' : IDL.Func([IDL.Text, IDL.Text, EntryId], [], []),
  'deleteCustomer' : IDL.Func([IDL.Text, IDL.Text, CustomerId], [], []),
  'deleteHuskBatchEntry' : IDL.Func([IDL.Text, IDL.Text, EntryId], [], []),
  'deleteVehicle' : IDL.Func([IDL.Text, IDL.Text, VehicleId], [], []),
  'getAllCoconutBatchEntries' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CoconutBatchEntry)],
      ['query'],
    ),
  'getAllCoconutCustomers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CustomerV2)],
      ['query'],
    ),
  'getAllCustomers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CustomerV2)],
      ['query'],
    ),
  'getAllHuskBatchEntries' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(HuskBatchEntry)],
      ['query'],
    ),
  'getAllHuskCustomers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(CustomerV2)],
      ['query'],
    ),
  'getAllNotes' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Note)], ['query']),
  'getAllVehicles' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Vehicle)],
      ['query'],
    ),
  'getCoconutBatchReport' : IDL.Func(
      [IDL.Text, IDL.Text, CoconutBatchReportFilter],
      [CoconutBatchReport],
      ['query'],
    ),
  'getHuskBatchReport' : IDL.Func(
      [IDL.Text, IDL.Text, ReportFilter],
      [HuskBatchReport],
      ['query'],
    ),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Opt(
          IDL.Record({
            'username' : IDL.Text,
            'name' : IDL.Text,
            'role' : UserRole,
          })
        ),
      ],
      [],
    ),
  'updateCoconutBatchEntry' : IDL.Func(
      [IDL.Text, IDL.Text, EntryId, CoconutBatchEntryInput],
      [],
      [],
    ),
  'updateCoconutBatchPayment' : IDL.Func(
      [IDL.Text, IDL.Text, EntryId, PaymentStatus, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'updateCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, CustomerId, CustomerInputV2],
      [],
      [],
    ),
  'updateHuskBatchEntry' : IDL.Func(
      [IDL.Text, IDL.Text, EntryId, HuskBatchEntryInput],
      [],
      [],
    ),
  'updateHuskBatchPayment' : IDL.Func(
      [IDL.Text, IDL.Text, EntryId, PaymentStatus, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CustomerId = IDL.Nat;
  const CoconutType = IDL.Variant({
    'tallu' : IDL.Null,
    'rasi' : IDL.Null,
    'others' : IDL.Null,
  });
  const CoconutItem = IDL.Record({
    'specifyType' : IDL.Text,
    'coconutType' : CoconutType,
    'quantity' : IDL.Nat,
  });
  const CoconutBatchEntryInput = IDL.Record({
    'customerName' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'createdByName' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : CustomerId,
    'items' : IDL.Vec(CoconutItem),
  });
  const EntryId = IDL.Nat;
  const CustomerInputV2 = IDL.Record({
    'customerType' : IDL.Text,
    'name' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const ItemType = IDL.Variant({
    'dry' : IDL.Null,
    'wet' : IDL.Null,
    'motta' : IDL.Null,
    'both' : IDL.Null,
    'husk' : IDL.Null,
    'others' : IDL.Null,
  });
  const HuskItem = IDL.Record({ 'itemType' : ItemType, 'quantity' : IDL.Nat });
  const HuskBatchEntryInput = IDL.Record({
    'customerName' : IDL.Text,
    'vehicleNumber' : IDL.Text,
    'createdByName' : IDL.Text,
    'notes' : IDL.Text,
    'customerId' : CustomerId,
    'items' : IDL.Vec(HuskItem),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'staff' : IDL.Null,
    'driver' : IDL.Null,
  });
  const VehicleId = IDL.Nat;
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
  });
  const Time = IDL.Int;
  const CoconutBatchEntry = IDL.Record({
    'id' : EntryId,
    'customerName' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'vehicleNumber' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'createdByName' : IDL.Text,
    'notes' : IDL.Text,
    'lastModifiedAt' : IDL.Opt(Time),
    'customerId' : CustomerId,
    'items' : IDL.Vec(CoconutItem),
    'paymentAmount' : IDL.Opt(IDL.Nat),
    'lastModifiedByName' : IDL.Opt(IDL.Text),
  });
  const CustomerV2 = IDL.Record({
    'id' : CustomerId,
    'customerType' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const HuskBatchEntry = IDL.Record({
    'id' : EntryId,
    'customerName' : IDL.Text,
    'paymentStatus' : PaymentStatus,
    'vehicleNumber' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'createdByName' : IDL.Text,
    'notes' : IDL.Text,
    'lastModifiedAt' : IDL.Opt(Time),
    'customerId' : CustomerId,
    'items' : IDL.Vec(HuskItem),
    'paymentAmount' : IDL.Opt(IDL.Nat),
    'lastModifiedByName' : IDL.Opt(IDL.Text),
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
  });
  const Vehicle = IDL.Record({
    'id' : VehicleId,
    'vehicleNumber' : IDL.Text,
    'usageCount' : IDL.Nat,
    'lastUsed' : Time,
  });
  const CoconutBatchReportFilter = IDL.Record({
    'paymentStatus' : IDL.Opt(PaymentStatus),
    'endDate' : IDL.Opt(Time),
    'coconutType' : IDL.Opt(CoconutType),
    'vehicleNumber' : IDL.Opt(IDL.Text),
    'customerId' : IDL.Opt(CustomerId),
    'startDate' : IDL.Opt(Time),
  });
  const CoconutBatchReport = IDL.Record({
    'pendingCount' : IDL.Nat,
    'totalPaymentAmount' : IDL.Nat,
    'entries' : IDL.Vec(CoconutBatchEntry),
    'paidCount' : IDL.Nat,
    'totalQuantity' : IDL.Nat,
  });
  const ReportFilter = IDL.Record({
    'paymentStatus' : IDL.Opt(PaymentStatus),
    'endDate' : IDL.Opt(Time),
    'userId' : IDL.Opt(IDL.Text),
    'vehicleNumber' : IDL.Opt(IDL.Text),
    'itemType' : IDL.Opt(ItemType),
    'customerId' : IDL.Opt(CustomerId),
    'startDate' : IDL.Opt(Time),
  });
  const HuskBatchReport = IDL.Record({
    'pendingCount' : IDL.Nat,
    'totalPaymentAmount' : IDL.Nat,
    'entries' : IDL.Vec(HuskBatchEntry),
    'paidCount' : IDL.Nat,
    'totalQuantity' : IDL.Nat,
  });
  
  return IDL.Service({
    'addCoconutBatchEntry' : IDL.Func(
        [IDL.Text, IDL.Text, CoconutBatchEntryInput],
        [EntryId],
        [],
      ),
    'addCoconutBatchEntryWithDate' : IDL.Func(
        [IDL.Text, IDL.Text, CoconutBatchEntryInput, IDL.Int],
        [EntryId],
        [],
      ),
    'addCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, CustomerInputV2],
        [CustomerId],
        [],
      ),
    'addHuskBatchEntry' : IDL.Func(
        [IDL.Text, IDL.Text, HuskBatchEntryInput],
        [EntryId],
        [],
      ),
    'addHuskBatchEntryWithDate' : IDL.Func(
        [IDL.Text, IDL.Text, HuskBatchEntryInput, IDL.Int],
        [EntryId],
        [],
      ),
    'addNote' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'adminChangeUserPin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminChangeUserRole' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, UserRole],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminCreateUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, UserRole],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminListUsers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Opt(
            IDL.Vec(
              IDL.Record({
                'username' : IDL.Text,
                'name' : IDL.Text,
                'role' : UserRole,
              })
            )
          ),
        ],
        ['query'],
      ),
    'changeOwnPin' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteCoconutBatchEntry' : IDL.Func([IDL.Text, IDL.Text, EntryId], [], []),
    'deleteCustomer' : IDL.Func([IDL.Text, IDL.Text, CustomerId], [], []),
    'deleteHuskBatchEntry' : IDL.Func([IDL.Text, IDL.Text, EntryId], [], []),
    'deleteVehicle' : IDL.Func([IDL.Text, IDL.Text, VehicleId], [], []),
    'getAllCoconutBatchEntries' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CoconutBatchEntry)],
        ['query'],
      ),
    'getAllCoconutCustomers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CustomerV2)],
        ['query'],
      ),
    'getAllCustomers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CustomerV2)],
        ['query'],
      ),
    'getAllHuskBatchEntries' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(HuskBatchEntry)],
        ['query'],
      ),
    'getAllHuskCustomers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(CustomerV2)],
        ['query'],
      ),
    'getAllNotes' : IDL.Func([IDL.Text, IDL.Text], [IDL.Vec(Note)], ['query']),
    'getAllVehicles' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Vehicle)],
        ['query'],
      ),
    'getCoconutBatchReport' : IDL.Func(
        [IDL.Text, IDL.Text, CoconutBatchReportFilter],
        [CoconutBatchReport],
        ['query'],
      ),
    'getHuskBatchReport' : IDL.Func(
        [IDL.Text, IDL.Text, ReportFilter],
        [HuskBatchReport],
        ['query'],
      ),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Opt(
            IDL.Record({
              'username' : IDL.Text,
              'name' : IDL.Text,
              'role' : UserRole,
            })
          ),
        ],
        [],
      ),
    'updateCoconutBatchEntry' : IDL.Func(
        [IDL.Text, IDL.Text, EntryId, CoconutBatchEntryInput],
        [],
        [],
      ),
    'updateCoconutBatchPayment' : IDL.Func(
        [IDL.Text, IDL.Text, EntryId, PaymentStatus, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'updateCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, CustomerId, CustomerInputV2],
        [],
        [],
      ),
    'updateHuskBatchEntry' : IDL.Func(
        [IDL.Text, IDL.Text, EntryId, HuskBatchEntryInput],
        [],
        [],
      ),
    'updateHuskBatchPayment' : IDL.Func(
        [IDL.Text, IDL.Text, EntryId, PaymentStatus, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };