/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HuskItem {
    itemType: ItemType;
    quantity: bigint;
}
export type VehicleId = bigint;
export type Time = bigint;
export interface CustomerV2 {
    id: CustomerId;
    customerType: string;
    name: string;
    createdAt: Time;
    phone: string;
    location: string;
}
export interface CoconutBatchEntryInput {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    customerId: CustomerId;
    items: Array<CoconutItem>;
}
export interface HuskBatchReport {
    pendingCount: bigint;
    totalPaymentAmount: bigint;
    entries: Array<HuskBatchEntry>;
    paidCount: bigint;
    totalQuantity: bigint;
}
export interface Vehicle {
    id: VehicleId;
    vehicleNumber: string;
    usageCount: bigint;
    lastUsed: Time;
}
export interface ReportFilter {
    paymentStatus?: PaymentStatus;
    endDate?: Time;
    userId?: string;
    vehicleNumber?: string;
    itemType?: ItemType;
    customerId?: CustomerId;
    startDate?: Time;
}
export interface HuskBatchEntryInput {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    customerId: CustomerId;
    items: Array<HuskItem>;
}
export interface CustomerInputV2 {
    customerType: string;
    name: string;
    phone: string;
    location: string;
}
export interface CoconutItem {
    specifyType: string;
    coconutType: CoconutType;
    quantity: bigint;
}
export type EntryId = bigint;
export type CustomerId = bigint;
export interface HuskBatchEntry {
    id: EntryId;
    customerName: string;
    paymentStatus: PaymentStatus;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    lastModifiedAt?: Time;
    customerId: CustomerId;
    items: Array<HuskItem>;
    paymentAmount?: bigint;
    lastModifiedByName?: string;
}
export interface CoconutBatchReport {
    pendingCount: bigint;
    totalPaymentAmount: bigint;
    entries: Array<CoconutBatchEntry>;
    paidCount: bigint;
    totalQuantity: bigint;
}
export interface CoconutBatchReportFilter {
    paymentStatus?: PaymentStatus;
    endDate?: Time;
    coconutType?: CoconutType;
    vehicleNumber?: string;
    customerId?: CustomerId;
    startDate?: Time;
}
export interface CoconutBatchEntry {
    id: EntryId;
    customerName: string;
    paymentStatus: PaymentStatus;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    lastModifiedAt?: Time;
    customerId: CustomerId;
    items: Array<CoconutItem>;
    paymentAmount?: bigint;
    lastModifiedByName?: string;
}
export interface Note {
    id: bigint;
    content: string;
    createdAt: Time;
    createdBy: Principal;
}
export enum CoconutType {
    tallu = "tallu",
    rasi = "rasi",
    others = "others"
}
export enum ItemType {
    dry = "dry",
    wet = "wet",
    motta = "motta",
    both = "both",
    husk = "husk",
    others = "others"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid"
}
export enum UserRole {
    admin = "admin",
    staff = "staff",
    driver = "driver"
}
export interface backendInterface {
    addCoconutBatchEntry(username: string, pin: string, input: CoconutBatchEntryInput): Promise<EntryId>;
    addCoconutBatchEntryWithDate(username: string, pin: string, input: CoconutBatchEntryInput, createdAtMs: bigint): Promise<EntryId>;
    addCustomer(username: string, pin: string, input: CustomerInputV2): Promise<CustomerId>;
    addHuskBatchEntry(username: string, pin: string, input: HuskBatchEntryInput): Promise<EntryId>;
    addHuskBatchEntryWithDate(username: string, pin: string, input: HuskBatchEntryInput, createdAtMs: bigint): Promise<EntryId>;
    addNote(username: string, pin: string, content: string): Promise<bigint>;
    adminChangeUserPin(adminUsername: string, adminPin: string, targetUsername: string, newPin: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminChangeUserRole(adminUsername: string, adminPin: string, targetUsername: string, newRole: UserRole): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminCreateUser(adminUsername: string, adminPin: string, newUsername: string, newPin: string, name: string, role: UserRole): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDeleteUser(adminUsername: string, adminPin: string, targetUsername: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminListUsers(adminUsername: string, adminPin: string): Promise<Array<{
        username: string;
        name: string;
        role: UserRole;
    }> | null>;
    changeOwnPin(username: string, oldPin: string, newPin: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    deleteCoconutBatchEntry(username: string, pin: string, id: EntryId): Promise<void>;
    deleteCustomer(username: string, pin: string, id: CustomerId): Promise<void>;
    deleteHuskBatchEntry(username: string, pin: string, id: EntryId): Promise<void>;
    deleteVehicle(username: string, pin: string, id: VehicleId): Promise<void>;
    getAllCoconutBatchEntries(username: string, pin: string): Promise<Array<CoconutBatchEntry>>;
    getAllCoconutCustomers(username: string, pin: string): Promise<Array<CustomerV2>>;
    getAllCustomers(username: string, pin: string): Promise<Array<CustomerV2>>;
    getAllHuskBatchEntries(username: string, pin: string): Promise<Array<HuskBatchEntry>>;
    getAllHuskCustomers(username: string, pin: string): Promise<Array<CustomerV2>>;
    getAllNotes(username: string, pin: string): Promise<Array<Note>>;
    getAllVehicles(username: string, pin: string): Promise<Array<Vehicle>>;
    getCoconutBatchReport(username: string, pin: string, filter: CoconutBatchReportFilter): Promise<CoconutBatchReport>;
    getHuskBatchReport(username: string, pin: string, filter: ReportFilter): Promise<HuskBatchReport>;
    loginUser(username: string, pin: string): Promise<{
        username: string;
        name: string;
        role: UserRole;
    } | null>;
    updateCoconutBatchEntry(username: string, pin: string, id: EntryId, input: CoconutBatchEntryInput): Promise<void>;
    updateCoconutBatchPayment(username: string, pin: string, id: EntryId, status: PaymentStatus, amount: bigint | null): Promise<void>;
    updateCustomer(username: string, pin: string, id: CustomerId, input: CustomerInputV2): Promise<void>;
    updateHuskBatchEntry(username: string, pin: string, id: EntryId, input: HuskBatchEntryInput): Promise<void>;
    updateHuskBatchPayment(username: string, pin: string, id: EntryId, status: PaymentStatus, amount: bigint | null): Promise<void>;
}
import type { CoconutBatchEntry as _CoconutBatchEntry, CoconutBatchEntryInput as _CoconutBatchEntryInput, CoconutBatchReport as _CoconutBatchReport, CoconutBatchReportFilter as _CoconutBatchReportFilter, CoconutItem as _CoconutItem, CoconutType as _CoconutType, CustomerId as _CustomerId, EntryId as _EntryId, HuskBatchEntry as _HuskBatchEntry, HuskBatchEntryInput as _HuskBatchEntryInput, HuskBatchReport as _HuskBatchReport, HuskItem as _HuskItem, ItemType as _ItemType, PaymentStatus as _PaymentStatus, ReportFilter as _ReportFilter, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addCoconutBatchEntry(arg0: string, arg1: string, arg2: CoconutBatchEntryInput): Promise<EntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoconutBatchEntry(arg0, arg1, to_candid_CoconutBatchEntryInput_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoconutBatchEntry(arg0, arg1, to_candid_CoconutBatchEntryInput_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addCoconutBatchEntryWithDate(arg0: string, arg1: string, arg2: CoconutBatchEntryInput, arg3: bigint): Promise<EntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoconutBatchEntryWithDate(arg0, arg1, to_candid_CoconutBatchEntryInput_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoconutBatchEntryWithDate(arg0, arg1, to_candid_CoconutBatchEntryInput_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addCustomer(arg0: string, arg1: string, arg2: CustomerInputV2): Promise<CustomerId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async addHuskBatchEntry(arg0: string, arg1: string, arg2: HuskBatchEntryInput): Promise<EntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addHuskBatchEntry(arg0, arg1, to_candid_HuskBatchEntryInput_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHuskBatchEntry(arg0, arg1, to_candid_HuskBatchEntryInput_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addHuskBatchEntryWithDate(arg0: string, arg1: string, arg2: HuskBatchEntryInput, arg3: bigint): Promise<EntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addHuskBatchEntryWithDate(arg0, arg1, to_candid_HuskBatchEntryInput_n8(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHuskBatchEntryWithDate(arg0, arg1, to_candid_HuskBatchEntryInput_n8(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async addNote(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(arg0, arg1, arg2);
            return result;
        }
    }
    async adminChangeUserPin(arg0: string, arg1: string, arg2: string, arg3: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminChangeUserPin(arg0, arg1, arg2, arg3);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminChangeUserPin(arg0, arg1, arg2, arg3);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminChangeUserRole(arg0: string, arg1: string, arg2: string, arg3: UserRole): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminChangeUserRole(arg0, arg1, arg2, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminChangeUserRole(arg0, arg1, arg2, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminCreateUser(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: UserRole): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateUser(arg0, arg1, arg2, arg3, arg4, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg5));
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateUser(arg0, arg1, arg2, arg3, arg4, to_candid_UserRole_n16(this._uploadFile, this._downloadFile, arg5));
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteUser(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteUser(arg0, arg1, arg2);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteUser(arg0, arg1, arg2);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListUsers(arg0: string, arg1: string): Promise<Array<{
        username: string;
        name: string;
        role: UserRole;
    }> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUsers(arg0, arg1);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUsers(arg0, arg1);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async changeOwnPin(arg0: string, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.changeOwnPin(arg0, arg1, arg2);
                return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeOwnPin(arg0, arg1, arg2);
            return from_candid_variant_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteCoconutBatchEntry(arg0: string, arg1: string, arg2: EntryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoconutBatchEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoconutBatchEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCustomer(arg0: string, arg1: string, arg2: CustomerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteHuskBatchEntry(arg0: string, arg1: string, arg2: EntryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHuskBatchEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHuskBatchEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteVehicle(arg0: string, arg1: string, arg2: VehicleId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVehicle(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVehicle(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllCoconutBatchEntries(arg0: string, arg1: string): Promise<Array<CoconutBatchEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoconutBatchEntries(arg0, arg1);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoconutBatchEntries(arg0, arg1);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCoconutCustomers(arg0: string, arg1: string): Promise<Array<CustomerV2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoconutCustomers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoconutCustomers(arg0, arg1);
            return result;
        }
    }
    async getAllCustomers(arg0: string, arg1: string): Promise<Array<CustomerV2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers(arg0, arg1);
            return result;
        }
    }
    async getAllHuskBatchEntries(arg0: string, arg1: string): Promise<Array<HuskBatchEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHuskBatchEntries(arg0, arg1);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHuskBatchEntries(arg0, arg1);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHuskCustomers(arg0: string, arg1: string): Promise<Array<CustomerV2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHuskCustomers(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHuskCustomers(arg0, arg1);
            return result;
        }
    }
    async getAllNotes(arg0: string, arg1: string): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes(arg0, arg1);
            return result;
        }
    }
    async getAllVehicles(arg0: string, arg1: string): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVehicles(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVehicles(arg0, arg1);
            return result;
        }
    }
    async getCoconutBatchReport(arg0: string, arg1: string, arg2: CoconutBatchReportFilter): Promise<CoconutBatchReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoconutBatchReport(arg0, arg1, to_candid_CoconutBatchReportFilter_n44(this._uploadFile, this._downloadFile, arg2));
                return from_candid_CoconutBatchReport_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoconutBatchReport(arg0, arg1, to_candid_CoconutBatchReportFilter_n44(this._uploadFile, this._downloadFile, arg2));
            return from_candid_CoconutBatchReport_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHuskBatchReport(arg0: string, arg1: string, arg2: ReportFilter): Promise<HuskBatchReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getHuskBatchReport(arg0, arg1, to_candid_ReportFilter_n50(this._uploadFile, this._downloadFile, arg2));
                return from_candid_HuskBatchReport_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHuskBatchReport(arg0, arg1, to_candid_ReportFilter_n50(this._uploadFile, this._downloadFile, arg2));
            return from_candid_HuskBatchReport_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<{
        username: string;
        name: string;
        role: UserRole;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCoconutBatchEntry(arg0: string, arg1: string, arg2: EntryId, arg3: CoconutBatchEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoconutBatchEntry(arg0, arg1, arg2, to_candid_CoconutBatchEntryInput_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoconutBatchEntry(arg0, arg1, arg2, to_candid_CoconutBatchEntryInput_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateCoconutBatchPayment(arg0: string, arg1: string, arg2: EntryId, arg3: PaymentStatus, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoconutBatchPayment(arg0, arg1, arg2, to_candid_PaymentStatus_n46(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoconutBatchPayment(arg0, arg1, arg2, to_candid_PaymentStatus_n46(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async updateCustomer(arg0: string, arg1: string, arg2: CustomerId, arg3: CustomerInputV2): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateHuskBatchEntry(arg0: string, arg1: string, arg2: EntryId, arg3: HuskBatchEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHuskBatchEntry(arg0, arg1, arg2, to_candid_HuskBatchEntryInput_n8(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHuskBatchEntry(arg0, arg1, arg2, to_candid_HuskBatchEntryInput_n8(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateHuskBatchPayment(arg0: string, arg1: string, arg2: EntryId, arg3: PaymentStatus, arg4: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHuskBatchPayment(arg0, arg1, arg2, to_candid_PaymentStatus_n46(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHuskBatchPayment(arg0, arg1, arg2, to_candid_PaymentStatus_n46(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n55(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
}
function from_candid_CoconutBatchEntry_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoconutBatchEntry): CoconutBatchEntry {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_CoconutBatchReport_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoconutBatchReport): CoconutBatchReport {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_CoconutItem_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoconutItem): CoconutItem {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_CoconutType_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoconutType): CoconutType {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_HuskBatchEntry_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HuskBatchEntry): HuskBatchEntry {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_HuskBatchReport_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HuskBatchReport): HuskBatchReport {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_HuskItem_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HuskItem): HuskItem {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_ItemType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemType): ItemType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<{
        username: string;
        name: string;
        role: _UserRole;
    }>]): Array<{
    username: string;
    name: string;
    role: UserRole;
}> | null {
    return value.length === 0 ? null : from_candid_vec_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        username: string;
        name: string;
        role: _UserRole;
    }]): {
    username: string;
    name: string;
    role: UserRole;
} | null {
    return value.length === 0 ? null : from_candid_record_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    username: string;
    name: string;
    role: _UserRole;
}): {
    username: string;
    name: string;
    role: UserRole;
} {
    return {
        username: value.username,
        name: value.name,
        role: from_candid_UserRole_n21(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntryId;
    customerName: string;
    paymentStatus: _PaymentStatus;
    vehicleNumber: string;
    createdAt: _Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    lastModifiedAt: [] | [_Time];
    customerId: _CustomerId;
    items: Array<_CoconutItem>;
    paymentAmount: [] | [bigint];
    lastModifiedByName: [] | [string];
}): {
    id: EntryId;
    customerName: string;
    paymentStatus: PaymentStatus;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    lastModifiedAt?: Time;
    customerId: CustomerId;
    items: Array<CoconutItem>;
    paymentAmount?: bigint;
    lastModifiedByName?: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        paymentStatus: from_candid_PaymentStatus_n26(_uploadFile, _downloadFile, value.paymentStatus),
        vehicleNumber: value.vehicleNumber,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        createdByName: value.createdByName,
        notes: value.notes,
        lastModifiedAt: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.lastModifiedAt)),
        customerId: value.customerId,
        items: from_candid_vec_n29(_uploadFile, _downloadFile, value.items),
        paymentAmount: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.paymentAmount)),
        lastModifiedByName: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.lastModifiedByName))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    specifyType: string;
    coconutType: _CoconutType;
    quantity: bigint;
}): {
    specifyType: string;
    coconutType: CoconutType;
    quantity: bigint;
} {
    return {
        specifyType: value.specifyType,
        coconutType: from_candid_CoconutType_n32(_uploadFile, _downloadFile, value.coconutType),
        quantity: value.quantity
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntryId;
    customerName: string;
    paymentStatus: _PaymentStatus;
    vehicleNumber: string;
    createdAt: _Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    lastModifiedAt: [] | [_Time];
    customerId: _CustomerId;
    items: Array<_HuskItem>;
    paymentAmount: [] | [bigint];
    lastModifiedByName: [] | [string];
}): {
    id: EntryId;
    customerName: string;
    paymentStatus: PaymentStatus;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    lastModifiedAt?: Time;
    customerId: CustomerId;
    items: Array<HuskItem>;
    paymentAmount?: bigint;
    lastModifiedByName?: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        paymentStatus: from_candid_PaymentStatus_n26(_uploadFile, _downloadFile, value.paymentStatus),
        vehicleNumber: value.vehicleNumber,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        createdByName: value.createdByName,
        notes: value.notes,
        lastModifiedAt: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.lastModifiedAt)),
        customerId: value.customerId,
        items: from_candid_vec_n39(_uploadFile, _downloadFile, value.items),
        paymentAmount: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.paymentAmount)),
        lastModifiedByName: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.lastModifiedByName))
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itemType: _ItemType;
    quantity: bigint;
}): {
    itemType: ItemType;
    quantity: bigint;
} {
    return {
        itemType: from_candid_ItemType_n42(_uploadFile, _downloadFile, value.itemType),
        quantity: value.quantity
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingCount: bigint;
    totalPaymentAmount: bigint;
    entries: Array<_CoconutBatchEntry>;
    paidCount: bigint;
    totalQuantity: bigint;
}): {
    pendingCount: bigint;
    totalPaymentAmount: bigint;
    entries: Array<CoconutBatchEntry>;
    paidCount: bigint;
    totalQuantity: bigint;
} {
    return {
        pendingCount: value.pendingCount,
        totalPaymentAmount: value.totalPaymentAmount,
        entries: from_candid_vec_n23(_uploadFile, _downloadFile, value.entries),
        paidCount: value.paidCount,
        totalQuantity: value.totalQuantity
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingCount: bigint;
    totalPaymentAmount: bigint;
    entries: Array<_HuskBatchEntry>;
    paidCount: bigint;
    totalQuantity: bigint;
}): {
    pendingCount: bigint;
    totalPaymentAmount: bigint;
    entries: Array<HuskBatchEntry>;
    paidCount: bigint;
    totalQuantity: bigint;
} {
    return {
        pendingCount: value.pendingCount,
        totalPaymentAmount: value.totalPaymentAmount,
        entries: from_candid_vec_n36(_uploadFile, _downloadFile, value.entries),
        paidCount: value.paidCount,
        totalQuantity: value.totalQuantity
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    staff: null;
} | {
    driver: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "staff" in value ? UserRole.staff : "driver" in value ? UserRole.driver : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tallu: null;
} | {
    rasi: null;
} | {
    others: null;
}): CoconutType {
    return "tallu" in value ? CoconutType.tallu : "rasi" in value ? CoconutType.rasi : "others" in value ? CoconutType.others : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dry: null;
} | {
    wet: null;
} | {
    motta: null;
} | {
    both: null;
} | {
    husk: null;
} | {
    others: null;
}): ItemType {
    return "dry" in value ? ItemType.dry : "wet" in value ? ItemType.wet : "motta" in value ? ItemType.motta : "both" in value ? ItemType.both : "husk" in value ? ItemType.husk : "others" in value ? ItemType.others : value;
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<{
    username: string;
    name: string;
    role: _UserRole;
}>): Array<{
    username: string;
    name: string;
    role: UserRole;
}> {
    return value.map((x)=>from_candid_record_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoconutBatchEntry>): Array<CoconutBatchEntry> {
    return value.map((x)=>from_candid_CoconutBatchEntry_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoconutItem>): Array<CoconutItem> {
    return value.map((x)=>from_candid_CoconutItem_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HuskBatchEntry>): Array<HuskBatchEntry> {
    return value.map((x)=>from_candid_HuskBatchEntry_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HuskItem>): Array<HuskItem> {
    return value.map((x)=>from_candid_HuskItem_n40(_uploadFile, _downloadFile, x));
}
function to_candid_CoconutBatchEntryInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoconutBatchEntryInput): _CoconutBatchEntryInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CoconutBatchReportFilter_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoconutBatchReportFilter): _CoconutBatchReportFilter {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_CoconutItem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoconutItem): _CoconutItem {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_CoconutType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoconutType): _CoconutType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_HuskBatchEntryInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HuskBatchEntryInput): _HuskBatchEntryInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_HuskItem_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HuskItem): _HuskItem {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ItemType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): _ItemType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_ReportFilter_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportFilter): _ReportFilter {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itemType: ItemType;
    quantity: bigint;
}): {
    itemType: _ItemType;
    quantity: bigint;
} {
    return {
        itemType: to_candid_ItemType_n13(_uploadFile, _downloadFile, value.itemType),
        quantity: value.quantity
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    customerId: CustomerId;
    items: Array<CoconutItem>;
}): {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    customerId: _CustomerId;
    items: Array<_CoconutItem>;
} {
    return {
        customerName: value.customerName,
        vehicleNumber: value.vehicleNumber,
        createdByName: value.createdByName,
        notes: value.notes,
        customerId: value.customerId,
        items: to_candid_vec_n3(_uploadFile, _downloadFile, value.items)
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus?: PaymentStatus;
    endDate?: Time;
    coconutType?: CoconutType;
    vehicleNumber?: string;
    customerId?: CustomerId;
    startDate?: Time;
}): {
    paymentStatus: [] | [_PaymentStatus];
    endDate: [] | [_Time];
    coconutType: [] | [_CoconutType];
    vehicleNumber: [] | [string];
    customerId: [] | [_CustomerId];
    startDate: [] | [_Time];
} {
    return {
        paymentStatus: value.paymentStatus ? candid_some(to_candid_PaymentStatus_n46(_uploadFile, _downloadFile, value.paymentStatus)) : candid_none(),
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        coconutType: value.coconutType ? candid_some(to_candid_CoconutType_n6(_uploadFile, _downloadFile, value.coconutType)) : candid_none(),
        vehicleNumber: value.vehicleNumber ? candid_some(value.vehicleNumber) : candid_none(),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none(),
        startDate: value.startDate ? candid_some(value.startDate) : candid_none()
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    specifyType: string;
    coconutType: CoconutType;
    quantity: bigint;
}): {
    specifyType: string;
    coconutType: _CoconutType;
    quantity: bigint;
} {
    return {
        specifyType: value.specifyType,
        coconutType: to_candid_CoconutType_n6(_uploadFile, _downloadFile, value.coconutType),
        quantity: value.quantity
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentStatus?: PaymentStatus;
    endDate?: Time;
    userId?: string;
    vehicleNumber?: string;
    itemType?: ItemType;
    customerId?: CustomerId;
    startDate?: Time;
}): {
    paymentStatus: [] | [_PaymentStatus];
    endDate: [] | [_Time];
    userId: [] | [string];
    vehicleNumber: [] | [string];
    itemType: [] | [_ItemType];
    customerId: [] | [_CustomerId];
    startDate: [] | [_Time];
} {
    return {
        paymentStatus: value.paymentStatus ? candid_some(to_candid_PaymentStatus_n46(_uploadFile, _downloadFile, value.paymentStatus)) : candid_none(),
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        userId: value.userId ? candid_some(value.userId) : candid_none(),
        vehicleNumber: value.vehicleNumber ? candid_some(value.vehicleNumber) : candid_none(),
        itemType: value.itemType ? candid_some(to_candid_ItemType_n13(_uploadFile, _downloadFile, value.itemType)) : candid_none(),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none(),
        startDate: value.startDate ? candid_some(value.startDate) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    customerId: CustomerId;
    items: Array<HuskItem>;
}): {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    customerId: _CustomerId;
    items: Array<_HuskItem>;
} {
    return {
        customerName: value.customerName,
        vehicleNumber: value.vehicleNumber,
        createdByName: value.createdByName,
        notes: value.notes,
        customerId: value.customerId,
        items: to_candid_vec_n10(_uploadFile, _downloadFile, value.items)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): {
    dry: null;
} | {
    wet: null;
} | {
    motta: null;
} | {
    both: null;
} | {
    husk: null;
} | {
    others: null;
} {
    return value == ItemType.dry ? {
        dry: null
    } : value == ItemType.wet ? {
        wet: null
    } : value == ItemType.motta ? {
        motta: null
    } : value == ItemType.both ? {
        both: null
    } : value == ItemType.husk ? {
        husk: null
    } : value == ItemType.others ? {
        others: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    staff: null;
} | {
    driver: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.staff ? {
        staff: null
    } : value == UserRole.driver ? {
        driver: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    paid: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoconutType): {
    tallu: null;
} | {
    rasi: null;
} | {
    others: null;
} {
    return value == CoconutType.tallu ? {
        tallu: null
    } : value == CoconutType.rasi ? {
        rasi: null
    } : value == CoconutType.others ? {
        others: null
    } : value;
}
function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<HuskItem>): Array<_HuskItem> {
    return value.map((x)=>to_candid_HuskItem_n11(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CoconutItem>): Array<_CoconutItem> {
    return value.map((x)=>to_candid_CoconutItem_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
