/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CoconutBatchReportFilter {
    endDate?: Time;
    coconutType?: CoconutType;
    vehicleNumber?: string;
    customerId?: CustomerId;
    startDate?: Time;
}
export interface HuskItem {
    itemType: ItemType;
    quantity: bigint;
}
export interface CoconutBatchReport {
    entries: Array<CoconutBatchEntry>;
    totalQuantity: bigint;
}
export type VehicleId = bigint;
export type Time = bigint;
export interface CoconutBatchEntryInput {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    customerId: CustomerId;
    items: Array<CoconutItem>;
}
export interface CoconutBatchEntry {
    id: EntryId;
    customerName: string;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    customerId: CustomerId;
    items: Array<CoconutItem>;
}
export interface HuskEntryInput {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    itemType: ItemType;
    quantity: bigint;
    customerId: CustomerId;
}
export interface HuskBatchReport {
    entries: Array<HuskBatchEntry>;
    totalQuantity: bigint;
}
export interface Vehicle {
    id: VehicleId;
    vehicleNumber: string;
    usageCount: bigint;
    lastUsed: Time;
}
export interface ReportFilter {
    endDate?: Time;
    userId?: Principal;
    vehicleNumber?: string;
    itemType?: ItemType;
    customerId?: CustomerId;
    startDate?: Time;
}
export interface HuskBatchEntryInput {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    customerId: CustomerId;
    items: Array<HuskItem>;
}
export interface CustomerInput {
    name: string;
    phone: string;
    location: string;
    customerType: string;
}
export interface Customer {
    id: CustomerId;
    name: string;
    createdAt: Time;
    phone: string;
    location: string;
    customerType: string;
}
export interface CoconutReport {
    entries: Array<CoconutEntry>;
    totalQuantity: bigint;
}
export type EntryId = bigint;
export interface CoconutItem {
    specifyType: string;
    coconutType: CoconutType;
    quantity: bigint;
}
export type CustomerId = bigint;
export interface CoconutEntryInput {
    customerName: string;
    specifyType: string;
    coconutType: CoconutType;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    quantity: bigint;
    customerId: CustomerId;
}
export interface HuskBatchEntry {
    id: EntryId;
    customerName: string;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    customerId: CustomerId;
    items: Array<HuskItem>;
}
export interface HuskEntry {
    id: EntryId;
    customerName: string;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    itemType: ItemType;
    quantity: bigint;
    customerId: CustomerId;
}
export interface CoconutEntry {
    id: EntryId;
    customerName: string;
    specifyType: string;
    coconutType: CoconutType;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    quantity: bigint;
    customerId: CustomerId;
}
export interface UserProfile {
    name: string;
}
export interface Note {
    id: bigint;
    content: string;
    createdAt: Time;
    createdBy: Principal;
}
export enum CoconutType {
    tallu = "tallu",
    rasi = "rasi",
    others = "others"
}
export enum ItemType {
    dry = "dry",
    wet = "wet",
    motta = "motta",
    both = "both",
    husk = "husk",
    others = "others"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCoconutBatchEntry(input: CoconutBatchEntryInput): Promise<EntryId>;
    addCoconutEntry(input: CoconutEntryInput): Promise<EntryId>;
    addCustomer(input: CustomerInput): Promise<CustomerId>;
    addEntry(input: HuskEntryInput): Promise<EntryId>;
    addHuskBatchEntry(input: HuskBatchEntryInput): Promise<EntryId>;
    addNote(content: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCoconutBatchEntry(id: EntryId): Promise<void>;
    deleteCoconutEntry(id: EntryId): Promise<void>;
    deleteCustomer(id: CustomerId): Promise<void>;
    deleteEntry(id: EntryId): Promise<void>;
    deleteHuskBatchEntry(id: EntryId): Promise<void>;
    deleteVehicle(id: VehicleId): Promise<void>;
    getAllCoconutBatchEntries(): Promise<Array<CoconutBatchEntry>>;
    getAllCoconutEntries(): Promise<Array<CoconutEntry>>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllEntries(): Promise<Array<HuskEntry>>;
    getAllHuskBatchEntries(): Promise<Array<HuskBatchEntry>>;
    getAllNotes(): Promise<Array<Note>>;
    getAllVehicles(): Promise<Array<Vehicle>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCoconutBatchEntry(id: EntryId): Promise<CoconutBatchEntry>;
    getCoconutBatchReport(filter: CoconutBatchReportFilter): Promise<CoconutBatchReport>;
    getCoconutEntry(id: EntryId): Promise<CoconutEntry>;
    getCoconutReport(filter: {
        endDate?: Time;
        coconutType?: CoconutType;
        vehicleNumber?: string;
        customerId?: CustomerId;
        startDate?: Time;
    }): Promise<CoconutReport>;
    getCustomer(id: CustomerId): Promise<Customer>;
    getEntry(id: EntryId): Promise<HuskEntry>;
    getHuskBatchEntry(id: EntryId): Promise<HuskBatchEntry>;
    getHuskBatchReport(filter: ReportFilter): Promise<HuskBatchReport>;
    getReport(filter: ReportFilter): Promise<{
        entries: Array<HuskEntry>;
        totalQuantity: bigint;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCoconutBatchEntry(id: EntryId, input: CoconutBatchEntryInput): Promise<void>;
    updateCoconutEntry(id: EntryId, input: CoconutEntryInput): Promise<void>;
    updateCustomer(id: CustomerId, input: CustomerInput): Promise<void>;
    updateEntry(id: EntryId, input: HuskEntryInput): Promise<void>;
    updateHuskBatchEntry(id: EntryId, input: HuskBatchEntryInput): Promise<void>;
}
import type { CoconutBatchEntry as _CoconutBatchEntry, CoconutBatchEntryInput as _CoconutBatchEntryInput, CoconutBatchReport as _CoconutBatchReport, CoconutBatchReportFilter as _CoconutBatchReportFilter, CoconutEntry as _CoconutEntry, CoconutEntryInput as _CoconutEntryInput, CoconutItem as _CoconutItem, CoconutReport as _CoconutReport, CoconutType as _CoconutType, CustomerId as _CustomerId, EntryId as _EntryId, HuskBatchEntry as _HuskBatchEntry, HuskBatchEntryInput as _HuskBatchEntryInput, HuskBatchReport as _HuskBatchReport, HuskEntry as _HuskEntry, HuskEntryInput as _HuskEntryInput, HuskItem as _HuskItem, ItemType as _ItemType, ReportFilter as _ReportFilter, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCoconutBatchEntry(arg0: CoconutBatchEntryInput): Promise<EntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoconutBatchEntry(to_candid_CoconutBatchEntryInput_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoconutBatchEntry(to_candid_CoconutBatchEntryInput_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addCoconutEntry(arg0: CoconutEntryInput): Promise<EntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoconutEntry(to_candid_CoconutEntryInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoconutEntry(to_candid_CoconutEntryInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addCustomer(arg0: CustomerInput): Promise<CustomerId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCustomer(arg0);
            return result;
        }
    }
    async addEntry(arg0: HuskEntryInput): Promise<EntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addEntry(to_candid_HuskEntryInput_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEntry(to_candid_HuskEntryInput_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addHuskBatchEntry(arg0: HuskBatchEntryInput): Promise<EntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.addHuskBatchEntry(to_candid_HuskBatchEntryInput_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHuskBatchEntry(to_candid_HuskBatchEntryInput_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addNote(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNote(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCoconutBatchEntry(arg0: EntryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoconutBatchEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoconutBatchEntry(arg0);
            return result;
        }
    }
    async deleteCoconutEntry(arg0: EntryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoconutEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoconutEntry(arg0);
            return result;
        }
    }
    async deleteCustomer(arg0: CustomerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCustomer(arg0);
            return result;
        }
    }
    async deleteEntry(arg0: EntryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEntry(arg0);
            return result;
        }
    }
    async deleteHuskBatchEntry(arg0: EntryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHuskBatchEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHuskBatchEntry(arg0);
            return result;
        }
    }
    async deleteVehicle(arg0: VehicleId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVehicle(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVehicle(arg0);
            return result;
        }
    }
    async getAllCoconutBatchEntries(): Promise<Array<CoconutBatchEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoconutBatchEntries();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoconutBatchEntries();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCoconutEntries(): Promise<Array<CoconutEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoconutEntries();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoconutEntries();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllEntries(): Promise<Array<HuskEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEntries();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEntries();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHuskBatchEntries(): Promise<Array<HuskBatchEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHuskBatchEntries();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHuskBatchEntries();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes();
            return result;
        }
    }
    async getAllVehicles(): Promise<Array<Vehicle>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVehicles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVehicles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoconutBatchEntry(arg0: EntryId): Promise<CoconutBatchEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoconutBatchEntry(arg0);
                return from_candid_CoconutBatchEntry_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoconutBatchEntry(arg0);
            return from_candid_CoconutBatchEntry_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoconutBatchReport(arg0: CoconutBatchReportFilter): Promise<CoconutBatchReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoconutBatchReport(to_candid_CoconutBatchReportFilter_n46(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CoconutBatchReport_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoconutBatchReport(to_candid_CoconutBatchReportFilter_n46(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CoconutBatchReport_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoconutEntry(arg0: EntryId): Promise<CoconutEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoconutEntry(arg0);
                return from_candid_CoconutEntry_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoconutEntry(arg0);
            return from_candid_CoconutEntry_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoconutReport(arg0: {
        endDate?: Time;
        coconutType?: CoconutType;
        vehicleNumber?: string;
        customerId?: CustomerId;
        startDate?: Time;
    }): Promise<CoconutReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoconutReport(to_candid_record_n47(this._uploadFile, this._downloadFile, arg0));
                return from_candid_CoconutReport_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoconutReport(to_candid_record_n47(this._uploadFile, this._downloadFile, arg0));
            return from_candid_CoconutReport_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomer(arg0: CustomerId): Promise<Customer> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomer(arg0);
            return result;
        }
    }
    async getEntry(arg0: EntryId): Promise<HuskEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntry(arg0);
                return from_candid_HuskEntry_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntry(arg0);
            return from_candid_HuskEntry_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHuskBatchEntry(arg0: EntryId): Promise<HuskBatchEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.getHuskBatchEntry(arg0);
                return from_candid_HuskBatchEntry_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHuskBatchEntry(arg0);
            return from_candid_HuskBatchEntry_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHuskBatchReport(arg0: ReportFilter): Promise<HuskBatchReport> {
        if (this.processError) {
            try {
                const result = await this.actor.getHuskBatchReport(to_candid_ReportFilter_n52(this._uploadFile, this._downloadFile, arg0));
                return from_candid_HuskBatchReport_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHuskBatchReport(to_candid_ReportFilter_n52(this._uploadFile, this._downloadFile, arg0));
            return from_candid_HuskBatchReport_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReport(arg0: ReportFilter): Promise<{
        entries: Array<HuskEntry>;
        totalQuantity: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getReport(to_candid_ReportFilter_n52(this._uploadFile, this._downloadFile, arg0));
                return from_candid_record_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReport(to_candid_ReportFilter_n52(this._uploadFile, this._downloadFile, arg0));
            return from_candid_record_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateCoconutBatchEntry(arg0: EntryId, arg1: CoconutBatchEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoconutBatchEntry(arg0, to_candid_CoconutBatchEntryInput_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoconutBatchEntry(arg0, to_candid_CoconutBatchEntryInput_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCoconutEntry(arg0: EntryId, arg1: CoconutEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoconutEntry(arg0, to_candid_CoconutEntryInput_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoconutEntry(arg0, to_candid_CoconutEntryInput_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCustomer(arg0: CustomerId, arg1: CustomerInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCustomer(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCustomer(arg0, arg1);
            return result;
        }
    }
    async updateEntry(arg0: EntryId, arg1: HuskEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEntry(arg0, to_candid_HuskEntryInput_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEntry(arg0, to_candid_HuskEntryInput_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHuskBatchEntry(arg0: EntryId, arg1: HuskBatchEntryInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHuskBatchEntry(arg0, to_candid_HuskBatchEntryInput_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHuskBatchEntry(arg0, to_candid_HuskBatchEntryInput_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_CoconutBatchEntry_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoconutBatchEntry): CoconutBatchEntry {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_CoconutBatchReport_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoconutBatchReport): CoconutBatchReport {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_CoconutEntry_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoconutEntry): CoconutEntry {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_CoconutItem_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoconutItem): CoconutItem {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_CoconutReport_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoconutReport): CoconutReport {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_CoconutType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoconutType): CoconutType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_HuskBatchEntry_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HuskBatchEntry): HuskBatchEntry {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_HuskBatchReport_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HuskBatchReport): HuskBatchReport {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_HuskEntry_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HuskEntry): HuskEntry {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_HuskItem_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HuskItem): HuskItem {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_ItemType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemType): ItemType {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntryId;
    customerName: string;
    vehicleNumber: string;
    createdAt: _Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    customerId: _CustomerId;
    items: Array<_CoconutItem>;
}): {
    id: EntryId;
    customerName: string;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    customerId: CustomerId;
    items: Array<CoconutItem>;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        vehicleNumber: value.vehicleNumber,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        createdByName: value.createdByName,
        notes: value.notes,
        customerId: value.customerId,
        items: from_candid_vec_n24(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    specifyType: string;
    coconutType: _CoconutType;
    quantity: bigint;
}): {
    specifyType: string;
    coconutType: CoconutType;
    quantity: bigint;
} {
    return {
        specifyType: value.specifyType,
        coconutType: from_candid_CoconutType_n27(_uploadFile, _downloadFile, value.coconutType),
        quantity: value.quantity
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntryId;
    customerName: string;
    specifyType: string;
    coconutType: _CoconutType;
    vehicleNumber: string;
    createdAt: _Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    quantity: bigint;
    customerId: _CustomerId;
}): {
    id: EntryId;
    customerName: string;
    specifyType: string;
    coconutType: CoconutType;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    quantity: bigint;
    customerId: CustomerId;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        specifyType: value.specifyType,
        coconutType: from_candid_CoconutType_n27(_uploadFile, _downloadFile, value.coconutType),
        vehicleNumber: value.vehicleNumber,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        createdByName: value.createdByName,
        notes: value.notes,
        quantity: value.quantity,
        customerId: value.customerId
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntryId;
    customerName: string;
    vehicleNumber: string;
    createdAt: _Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    itemType: _ItemType;
    quantity: bigint;
    customerId: _CustomerId;
}): {
    id: EntryId;
    customerName: string;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    itemType: ItemType;
    quantity: bigint;
    customerId: CustomerId;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        vehicleNumber: value.vehicleNumber,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        createdByName: value.createdByName,
        notes: value.notes,
        itemType: from_candid_ItemType_n35(_uploadFile, _downloadFile, value.itemType),
        quantity: value.quantity,
        customerId: value.customerId
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntryId;
    customerName: string;
    vehicleNumber: string;
    createdAt: _Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    customerId: _CustomerId;
    items: Array<_HuskItem>;
}): {
    id: EntryId;
    customerName: string;
    vehicleNumber: string;
    createdAt: Time;
    createdBy: Principal;
    createdByName: string;
    notes: string;
    customerId: CustomerId;
    items: Array<HuskItem>;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        vehicleNumber: value.vehicleNumber,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        createdByName: value.createdByName,
        notes: value.notes,
        customerId: value.customerId,
        items: from_candid_vec_n40(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itemType: _ItemType;
    quantity: bigint;
}): {
    itemType: ItemType;
    quantity: bigint;
} {
    return {
        itemType: from_candid_ItemType_n35(_uploadFile, _downloadFile, value.itemType),
        quantity: value.quantity
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entries: Array<_CoconutBatchEntry>;
    totalQuantity: bigint;
}): {
    entries: Array<CoconutBatchEntry>;
    totalQuantity: bigint;
} {
    return {
        entries: from_candid_vec_n21(_uploadFile, _downloadFile, value.entries),
        totalQuantity: value.totalQuantity
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entries: Array<_CoconutEntry>;
    totalQuantity: bigint;
}): {
    entries: Array<CoconutEntry>;
    totalQuantity: bigint;
} {
    return {
        entries: from_candid_vec_n29(_uploadFile, _downloadFile, value.entries),
        totalQuantity: value.totalQuantity
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entries: Array<_HuskBatchEntry>;
    totalQuantity: bigint;
}): {
    entries: Array<HuskBatchEntry>;
    totalQuantity: bigint;
} {
    return {
        entries: from_candid_vec_n37(_uploadFile, _downloadFile, value.entries),
        totalQuantity: value.totalQuantity
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entries: Array<_HuskEntry>;
    totalQuantity: bigint;
}): {
    entries: Array<HuskEntry>;
    totalQuantity: bigint;
} {
    return {
        entries: from_candid_vec_n32(_uploadFile, _downloadFile, value.entries),
        totalQuantity: value.totalQuantity
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tallu: null;
} | {
    rasi: null;
} | {
    others: null;
}): CoconutType {
    return "tallu" in value ? CoconutType.tallu : "rasi" in value ? CoconutType.rasi : "others" in value ? CoconutType.others : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    dry: null;
} | {
    wet: null;
} | {
    motta: null;
} | {
    both: null;
} | {
    husk: null;
} | {
    others: null;
}): ItemType {
    return "dry" in value ? ItemType.dry : "wet" in value ? ItemType.wet : "motta" in value ? ItemType.motta : "both" in value ? ItemType.both : "husk" in value ? ItemType.husk : "others" in value ? ItemType.others : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoconutBatchEntry>): Array<CoconutBatchEntry> {
    return value.map((x)=>from_candid_CoconutBatchEntry_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoconutItem>): Array<CoconutItem> {
    return value.map((x)=>from_candid_CoconutItem_n25(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoconutEntry>): Array<CoconutEntry> {
    return value.map((x)=>from_candid_CoconutEntry_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HuskEntry>): Array<HuskEntry> {
    return value.map((x)=>from_candid_HuskEntry_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HuskBatchEntry>): Array<HuskBatchEntry> {
    return value.map((x)=>from_candid_HuskBatchEntry_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HuskItem>): Array<HuskItem> {
    return value.map((x)=>from_candid_HuskItem_n41(_uploadFile, _downloadFile, x));
}
function to_candid_CoconutBatchEntryInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoconutBatchEntryInput): _CoconutBatchEntryInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CoconutBatchReportFilter_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoconutBatchReportFilter): _CoconutBatchReportFilter {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_CoconutEntryInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoconutEntryInput): _CoconutEntryInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_CoconutItem_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoconutItem): _CoconutItem {
    return to_candid_record_n5(_uploadFile, _downloadFile, value);
}
function to_candid_CoconutType_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoconutType): _CoconutType {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_HuskBatchEntryInput_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HuskBatchEntryInput): _HuskBatchEntryInput {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_HuskEntryInput_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HuskEntryInput): _HuskEntryInput {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_HuskItem_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HuskItem): _HuskItem {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_ItemType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): _ItemType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_ReportFilter_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReportFilter): _ReportFilter {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    itemType: ItemType;
    quantity: bigint;
    customerId: CustomerId;
}): {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    itemType: _ItemType;
    quantity: bigint;
    customerId: _CustomerId;
} {
    return {
        customerName: value.customerName,
        vehicleNumber: value.vehicleNumber,
        createdByName: value.createdByName,
        notes: value.notes,
        itemType: to_candid_ItemType_n12(_uploadFile, _downloadFile, value.itemType),
        quantity: value.quantity,
        customerId: value.customerId
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    customerId: CustomerId;
    items: Array<HuskItem>;
}): {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    customerId: _CustomerId;
    items: Array<_HuskItem>;
} {
    return {
        customerName: value.customerName,
        vehicleNumber: value.vehicleNumber,
        createdByName: value.createdByName,
        notes: value.notes,
        customerId: value.customerId,
        items: to_candid_vec_n16(_uploadFile, _downloadFile, value.items)
    };
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    itemType: ItemType;
    quantity: bigint;
}): {
    itemType: _ItemType;
    quantity: bigint;
} {
    return {
        itemType: to_candid_ItemType_n12(_uploadFile, _downloadFile, value.itemType),
        quantity: value.quantity
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    customerId: CustomerId;
    items: Array<CoconutItem>;
}): {
    customerName: string;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    customerId: _CustomerId;
    items: Array<_CoconutItem>;
} {
    return {
        customerName: value.customerName,
        vehicleNumber: value.vehicleNumber,
        createdByName: value.createdByName,
        notes: value.notes,
        customerId: value.customerId,
        items: to_candid_vec_n3(_uploadFile, _downloadFile, value.items)
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: Time;
    coconutType?: CoconutType;
    vehicleNumber?: string;
    customerId?: CustomerId;
    startDate?: Time;
}): {
    endDate: [] | [_Time];
    coconutType: [] | [_CoconutType];
    vehicleNumber: [] | [string];
    customerId: [] | [_CustomerId];
    startDate: [] | [_Time];
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        coconutType: value.coconutType ? candid_some(to_candid_CoconutType_n6(_uploadFile, _downloadFile, value.coconutType)) : candid_none(),
        vehicleNumber: value.vehicleNumber ? candid_some(value.vehicleNumber) : candid_none(),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none(),
        startDate: value.startDate ? candid_some(value.startDate) : candid_none()
    };
}
function to_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    specifyType: string;
    coconutType: CoconutType;
    quantity: bigint;
}): {
    specifyType: string;
    coconutType: _CoconutType;
    quantity: bigint;
} {
    return {
        specifyType: value.specifyType,
        coconutType: to_candid_CoconutType_n6(_uploadFile, _downloadFile, value.coconutType),
        quantity: value.quantity
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: Time;
    userId?: Principal;
    vehicleNumber?: string;
    itemType?: ItemType;
    customerId?: CustomerId;
    startDate?: Time;
}): {
    endDate: [] | [_Time];
    userId: [] | [Principal];
    vehicleNumber: [] | [string];
    itemType: [] | [_ItemType];
    customerId: [] | [_CustomerId];
    startDate: [] | [_Time];
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        userId: value.userId ? candid_some(value.userId) : candid_none(),
        vehicleNumber: value.vehicleNumber ? candid_some(value.vehicleNumber) : candid_none(),
        itemType: value.itemType ? candid_some(to_candid_ItemType_n12(_uploadFile, _downloadFile, value.itemType)) : candid_none(),
        customerId: value.customerId ? candid_some(value.customerId) : candid_none(),
        startDate: value.startDate ? candid_some(value.startDate) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    specifyType: string;
    coconutType: CoconutType;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    quantity: bigint;
    customerId: CustomerId;
}): {
    customerName: string;
    specifyType: string;
    coconutType: _CoconutType;
    vehicleNumber: string;
    createdByName: string;
    notes: string;
    quantity: bigint;
    customerId: _CustomerId;
} {
    return {
        customerName: value.customerName,
        specifyType: value.specifyType,
        coconutType: to_candid_CoconutType_n6(_uploadFile, _downloadFile, value.coconutType),
        vehicleNumber: value.vehicleNumber,
        createdByName: value.createdByName,
        notes: value.notes,
        quantity: value.quantity,
        customerId: value.customerId
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ItemType): {
    dry: null;
} | {
    wet: null;
} | {
    motta: null;
} | {
    both: null;
} | {
    husk: null;
} | {
    others: null;
} {
    return value == ItemType.dry ? {
        dry: null
    } : value == ItemType.wet ? {
        wet: null
    } : value == ItemType.motta ? {
        motta: null
    } : value == ItemType.both ? {
        both: null
    } : value == ItemType.husk ? {
        husk: null
    } : value == ItemType.others ? {
        others: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoconutType): {
    tallu: null;
} | {
    rasi: null;
} | {
    others: null;
} {
    return value == CoconutType.tallu ? {
        tallu: null
    } : value == CoconutType.rasi ? {
        rasi: null
    } : value == CoconutType.others ? {
        others: null
    } : value;
}
function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<HuskItem>): Array<_HuskItem> {
    return value.map((x)=>to_candid_HuskItem_n17(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CoconutItem>): Array<_CoconutItem> {
    return value.map((x)=>to_candid_CoconutItem_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
